(() => {
'use strict';
const scenarios={
 finance:{id:'FIN-01',title:'Recurring finance operating review',summary:'Prepare recurring operating review inputs with AI assistance while finance retains interpretation, adjustment, and final communication authority.',work:'Gather, reconcile, and summarize recurring operating inputs before review.',value:'Reduce manual preparation and expose unresolved variance sooner.',authority:'Finance owns interpretation, adjustments, and the final narrative.',boundary:'Approved sources only; no autonomous posting or external disclosure.',adoption:'Named finance owner, review checklist, examples, and feedback cadence.',evidence:'Completeness, preparation effort, rework, review confidence, and retained use.',owner:'Finance workflow owner'},
 people:{id:'PPL-02',title:'Employee onboarding preparation',summary:'Assemble role-specific onboarding material with AI assistance while People leaders and managers retain policy interpretation, access decisions, and the employee experience.',work:'Assemble approved role, policy, systems, and team context into a usable onboarding path.',value:'Improve completeness and reduce repeated preparation without flattening role context.',authority:'People and the hiring manager own policy interpretation, access, timing, and exceptions.',boundary:'Approved policy and role sources only; no sensitive inference or autonomous access grant.',adoption:'Named People owner, manager checklist, new-hire feedback, and quarterly content review.',evidence:'Preparation time, completeness, manager rework, new-hire questions, and retained use.',owner:'People Operations workflow owner'},
 sales:{id:'GTM-03',title:'Account research preparation',summary:'Prepare account context and meeting hypotheses while commercial leaders retain prioritization, claims, commitments, and customer communication.',work:'Synthesize approved account, market, relationship, and product context before engagement.',value:'Reduce preparation time and improve consistency of relevant account context.',authority:'The account owner controls priorities, interpretation, claims, and customer commitments.',boundary:'Approved internal and public sources only; no invented facts or automated outreach.',adoption:'Account-owner templates, examples, peer review, and outcome feedback.',evidence:'Preparation effort, factual corrections, meeting usefulness, reuse, and owner confidence.',owner:'Commercial workflow owner'},
 success:{id:'CS-04',title:'Customer preparation brief',summary:'Assemble approved customer history and open themes while customer-facing leaders retain interpretation, commitments, and escalation authority.',work:'Prepare a concise customer context brief before a scheduled interaction.',value:'Improve preparation consistency and surface unresolved items earlier.',authority:'Customer-facing leaders own interpretation, commitments, escalation, and final communication.',boundary:'Approved customer systems only; no autonomous external response or unsupported recommendation.',adoption:'Named owner, pre-meeting checklist, feedback capture, and periodic quality review.',evidence:'Preparation effort, omissions, corrections, meeting usefulness, and retained use.',owner:'Customer workflow owner'},
 operations:{id:'OPS-05',title:'Operating decision follow-up',summary:'Draft structured follow-up from operating decisions while accountable leaders retain priority, assignment, timing, and escalation authority.',work:'Convert approved meeting decisions into clear owners, actions, dependencies, and follow-up.',value:'Reduce ambiguity and shorten the path from decision to visible execution.',authority:'Accountable leaders retain priority, assignment, timing, and escalation decisions.',boundary:'Approved meeting records only; no autonomous reassignment or policy interpretation.',adoption:'Decision template, owner confirmation, review cadence, and closure feedback.',evidence:'Owner clarity, missed actions, rework, closure rate, and retained use.',owner:'Operating review owner'}
};
const states=[
 {label:'Discovery candidate',reuse:'Keep the signal visible; do not standardize before ownership and evidence exist.',suffix:' Evidence is still observational; define the bounded test and owner.'},
 {label:'Bounded practice',reuse:'Keep bounded while evidence accumulates and exceptions become visible.',suffix:' Bounded proof; retain review and capture corrections, effort, and adoption.'},
 {label:'Reusable precedent',reuse:'Publish the reusable core and preserve legitimate local variation.',suffix:' Repeatable evidence; document the pattern, controls, training, and exception path.'}
];
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const select=$('#workflow-select'),range=$('#evidence-range'),replay=$('.replay-button'),record=$('.precedent-record'),folio=$('.folio');
function render(announce=true){const s=scenarios[select.value]||scenarios.finance; const e=states[Number(range.value)||0];
 $('#record-id').textContent=s.id; $('#record-title').textContent=s.title; $('#record-summary').textContent=s.summary; $('#disposition').textContent=e.label;
 ['work','value','authority','boundary','adoption'].forEach(k=>$('#field-'+k).textContent=s[k]); $('#field-evidence').textContent=s.evidence+e.suffix; $('#field-owner').textContent=s.owner; $('#field-reuse').textContent=e.reuse;
 $$('.range-labels span').forEach((x,i)=>x.classList.toggle('active',i===Number(range.value)));
 record.classList.remove('record-flash'); void record.offsetWidth; record.classList.add('record-flash');
 if(announce) $('#live').textContent=`${s.title}. ${e.label}. ${e.reuse}`;
}
function playFolio(){folio.classList.remove('is-playing'); void folio.offsetWidth; folio.classList.add('is-playing');}
select.addEventListener('change',()=>{render();playFolio()}); range.addEventListener('input',()=>render()); replay.addEventListener('click',()=>{render();playFolio()});
render(false); playFolio();
})();
